---
apiVersion: batch/v1
kind: Job
metadata:
  name: wrk-ddos
spec:
  template:
    metadata:
      name: wrk
    spec:
      containers:
        - name: wrk
          image: williamyeh/wrk
          command: ["/bin/sh", "-c"]
          args: ["wrk -t4 -c100 -d30s http://<TARGET-IP>:<PORT>"]
      restartPolicy: Never
  backoffLimit: 1
